# Generated by Django 6.0 on 2026-01-25 14:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentreResponsabilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Centres de responsabilité',
            },
        ),
        migrations.CreateModel(
            name='CompteCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_actif', models.BooleanField(default=True)),
                ('est_clos', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('94.1', 'Administration et logistique'), ('94.2', 'Médico technique'), ('94.3', 'Clinique'), ('94.4', 'Formation et Recherche')], max_length=10)),
                ('libelle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('CALCULATE', 'Calcul')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.IntegerField()),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CentreCout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('libelle', models.CharField(max_length=200)),
                ('type_centre', models.CharField(choices=[('NT_UO', "Non tarifaire avec Unité d'Œuvre"), ('NT_TF', 'Non tarifaire avec Taux de Frais'), ('CT_MT', 'Tarifaire Médico-technique'), ('CT_CL', 'Tarifaire Clinique')], max_length=10)),
                ('unite_oeuvre', models.CharField(blank=True, help_text="Ex: Nombre de consultations, journées d'hospitalisation", max_length=100)),
                ('tarif', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ordre_cascade', models.IntegerField(blank=True, help_text='Ordre de déversement pour la méthode cascade', null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('centre_responsabilite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.centreresponsabilite')),
            ],
            options={
                'verbose_name_plural': 'Centres de coûts',
                'ordering': ['code'],
                'unique_together': {('centre_responsabilite', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('numero_be_bc', models.CharField(blank=True, max_length=50, verbose_name='N° BE/BC')),
                ('numero_op', models.CharField(blank=True, max_length=50, verbose_name='N° OP')),
                ('numero_liquidation', models.CharField(blank=True, max_length=50, verbose_name='N° Liq')),
                ('designation', models.TextField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centre_cout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.centrecout')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges_crees', to=settings.AUTH_USER_MODEL)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.comptecharge')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.exercice')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='centreresponsabilite',
            name='fonction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.fonction'),
        ),
        migrations.AddField(
            model_name='fonction',
            name='hopital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.hopital'),
        ),
        migrations.AddField(
            model_name='exercice',
            name='hopital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.hopital'),
        ),
        migrations.AddField(
            model_name='comptecharge',
            name='hopital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.hopital'),
        ),
        migrations.CreateModel(
            name='CleRepartition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('centre_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cles_destination', to='analytics.centrecout')),
                ('centre_source', models.ForeignKey(limit_choices_to={'type_centre': 'NT_UO'}, on_delete=django.db.models.deletion.CASCADE, related_name='cles_source', to='analytics.centrecout')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.exercice')),
            ],
            options={
                'verbose_name': 'Clé de répartition',
                'verbose_name_plural': 'Clés de répartition',
                'unique_together': {('exercice', 'centre_source', 'centre_destination')},
            },
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(decimal_places=2, help_text="Nombre d'unités d'œuvre", max_digits=15)),
                ('centre_cout', models.ForeignKey(limit_choices_to={'type_centre__in': ['CT_MT', 'CT_CL']}, on_delete=django.db.models.deletion.CASCADE, to='analytics.centrecout')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.exercice')),
            ],
            options={
                'unique_together': {('exercice', 'centre_cout')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='centreresponsabilite',
            unique_together={('fonction', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='fonction',
            unique_together={('hopital', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='exercice',
            unique_together={('hopital', 'annee')},
        ),
        migrations.AlterUniqueTogether(
            name='comptecharge',
            unique_together={('hopital', 'numero')},
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('centre_cout', models.ForeignKey(limit_choices_to={'type_centre__in': ['CT_MT', 'CT_CL']}, on_delete=django.db.models.deletion.CASCADE, to='analytics.centrecout')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.exercice')),
            ],
            options={
                'unique_together': {('exercice', 'centre_cout')},
            },
        ),
        migrations.CreateModel(
            name='ResultatCalcul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charges_directes', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('charges_indirectes', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('charges_totales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('produits', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('volume_activite', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cout_revient_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('resultat_analytique', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('centre_cout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.centrecout')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.exercice')),
            ],
            options={
                'verbose_name_plural': 'Résultats de calcul',
                'unique_together': {('exercice', 'centre_cout')},
            },
        ),
    ]
