# Generated by Django 6.0 on 2026-03-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrecout',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='centrecout',
            name='libelle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='centrecout',
            name='unite_oeuvre',
            field=models.CharField(blank=True, help_text="Ex: Nombre de consultations, journées d'hospitalisation", max_length=50),
        ),
        migrations.AlterField(
            model_name='centreresponsabilite',
            name='libelle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='charge',
            name='designation',
            field=models.TextField(verbose_name=50),
        ),
        migrations.AlterField(
            model_name='charge',
            name='numero_be_bc',
            field=models.CharField(blank=True, max_length=30, verbose_name='N° BE/BC'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='numero_liquidation',
            field=models.CharField(blank=True, max_length=30, verbose_name='Liq'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='numero_op',
            field=models.CharField(blank=True, max_length=30, verbose_name='N° OP'),
        ),
        migrations.AlterField(
            model_name='comptecharge',
            name='libelle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fonction',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fonction',
            name='libelle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
