# Generated by Django 6.0 on 2026-03-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_centrecout_code_alter_centrecout_libelle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='designation',
            field=models.TextField(verbose_name=100),
        ),
    ]
