# Generated by Django 6.0 on 2026-03-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_charge_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='designation',
            field=models.CharField(max_length=100, verbose_name='Désignation'),
        ),
    ]
