# Generated by Django 6.0 on 2026-03-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_alter_charge_designation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comptecharge',
            options={'ordering': ['numero'], 'verbose_name_plural': 'Comptes de charges'},
        ),
        migrations.AlterModelOptions(
            name='hopital',
            options={'verbose_name_plural': 'Hopital'},
        ),
    ]
