# Generated by Django 6.0 on 2026-03-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_alter_comptecharge_options_alter_hopital_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hopital',
            options={'verbose_name_plural': 'Hopitaux'},
        ),
    ]
