# Generated by Django 6.0 on 2026-03-18 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_alter_hopital_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='centre_cout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.centrecout'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.comptecharge'),
        ),
    ]
