# Generated by Django 6.0 on 2026-03-18 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_alter_charge_centre_cout_alter_charge_compte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptecharge',
            name='hopital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analytics.hopital'),
        ),
    ]
