# Generated by Django 6.0 on 2026-03-18 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_alter_comptecharge_hopital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptecharge',
            name='hopital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.hopital'),
        ),
    ]
