# Generated by Django 6.0 on 2026-03-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_alter_comptecharge_hopital'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='periode',
            field=models.IntegerField(default=1, help_text='Mois de saisie (1-12)'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='produit',
            unique_together={('exercice', 'centre_cout', 'periode')},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['centre_cout__code', 'periode']},
        ),
    ]
