# Generated by Django 6.0 on 2026-03-21 01:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_activite_periode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hopital',
            field=models.ForeignKey(blank=True, help_text="Hôpital d'appartenance (vide = accès à tous les hôpitaux)", null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.hopital'),
        ),
        migrations.AlterField(
            model_name='activite',
            name='periode',
            field=models.IntegerField(help_text='Mois de saisie (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='periode',
            field=models.IntegerField(help_text='Mois de saisie (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
