# Generated by Django 6.0 on 2026-03-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_userprofile_add_hopital'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='type_produit',
            field=models.CharField(
                choices=[
                    ('ORDINAIRE', 'Produits ordinaires'),
                    ('SUPPLETIF', 'Produits suppletifs'),
                    ('AUTRE', 'Autres produits'),
                    ('SUBVENTION_EXP', "Subvention d'exploitation"),
                    ('AUTRE_SUBVENTION', 'Autres subventions'),
                ],
                default='ORDINAIRE',
                help_text='Nature du produit saisi',
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name='produit',
            unique_together={('exercice', 'centre_cout', 'periode', 'type_produit')},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['centre_cout__code', 'periode', 'type_produit']},
        ),
    ]