# Generated by Django 6.0 on 2026-03-23 00:00

from django.db import migrations, models
import django.db.models.deletion


def seed_default_hospital_roles(apps, schema_editor):
    Hopital = apps.get_model('analytics', 'Hopital')
    HopitalRole = apps.get_model('analytics', 'HopitalRole')
    UserProfile = apps.get_model('analytics', 'UserProfile')

    defaults = [
        ('controleur', 'Contrôleur de Gestion', [
            'manage_users',
            'manage_configuration',
            'enter_charges',
            'enter_products',
            'enter_activities',
            'run_calculations',
            'view_results',
            'export_reports',
        ]),
        ('directeur', 'Directeur', [
            'view_results',
            'export_reports',
        ]),
        ('responsable_financier', 'Responsable Financier', [
            'view_results',
            'export_reports',
            'run_calculations',
        ]),
        ('comptable', 'Comptable Analytique', [
            'enter_charges',
            'view_results',
        ]),
        ('agent_saisie', 'Agent de Saisie', [
            'enter_charges',
            'enter_products',
            'enter_activities',
        ]),
    ]

    for hopital in Hopital.objects.all():
        role_map = {}
        for code, libelle, permissions in defaults:
            role, _ = HopitalRole.objects.get_or_create(
                hopital=hopital,
                code=code,
                defaults={
                    'libelle': libelle,
                    'permissions': permissions,
                    'est_actif': True,
                }
            )
            role_map[code] = role

        for profile in UserProfile.objects.filter(hopital=hopital, hopital_role__isnull=True):
            matched_role = role_map.get(profile.role)
            if matched_role:
                profile.hopital_role = matched_role
                profile.save(update_fields=['hopital_role'])


def unseed_default_hospital_roles(apps, schema_editor):
    HopitalRole = apps.get_model('analytics', 'HopitalRole')
    HopitalRole.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_produit_type_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='HopitalRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('libelle', models.CharField(max_length=100)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('est_actif', models.BooleanField(default=True)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='analytics.hopital')),
            ],
            options={
                'verbose_name': 'Role hopital',
                'verbose_name_plural': 'Roles hopitaux',
                'ordering': ['hopital__nom', 'libelle'],
                'unique_together': {('hopital', 'code')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hopital_role',
            field=models.ForeignKey(blank=True, help_text='Role specifique defini pour cet hopital', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='analytics.hopitalrole'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('controleur', 'Contrôleur de Gestion'), ('directeur', 'Directeur'), ('responsable_financier', 'Responsable Financier'), ('comptable', 'Comptable Analytique'), ('agent_saisie', 'Agent de Saisie')], max_length=30),
        ),
        migrations.RunPython(seed_default_hospital_roles, unseed_default_hospital_roles),
    ]
